import { Project } from "@/lib/models/project.model";

export const sidebarLinks = [
  {
    imgURL: "/assets/home.svg",
    route: "",
    label: "Dashboard",
  },
  {
    imgURL: "/assets/discuss.svg",
    route: "/ondiscuss",
    label: "OnDiscuss",
  },
  {
    imgURL: "/assets/running.svg",
    route: "/running",
    label: "Running",
  },
  {
    imgURL: "/assets/finished.svg",
    route: "/finished",
    label: "Finished",
  },
  {
    imgURL: "/assets/cancelled.svg",
    route: "/cancelled",
    label: "Cancelled",
  },
];

export const dummyTableData: Project[] = [
  {
    _id: "1",
    no_penawaran: "PNW1",
    project_name: "Project 1 daaaa",
    client_name: "Customer A",
    alamat_sampling: "Location 1 dad",
    contact_person: "Contact Person 1",
    valuasi_proyek: 10000,
    created_at: "2023-10-14",
  },
  {
    _id: "2",
    no_penawaran: "PNW2",
    project_name: "Project 2",
    client_name: "Customer B",
    alamat_sampling: "Location 2",
    contact_person: "Contact Person 2",
    valuasi_proyek: 15000,
    created_at: "2023-10-14",
  },
  {
    _id: "3",
    no_penawaran: "PNW3",
    project_name: "Project 3",
    client_name: "Customer C",
    alamat_sampling: "Location 3",
    contact_person: "Contact Person 3",
    valuasi_proyek: 20000,
    created_at: "2023-10-14",
  },
  {
    _id: "4",
    no_penawaran: "PNW4",
    project_name: "Project 4",
    client_name: "Customer D",
    alamat_sampling: "Location 4",
    contact_person: "Contact Person 4",
    valuasi_proyek: 25000,
    created_at: "2023-10-14",
  },
  {
    _id: "5",
    no_penawaran: "PNW5",
    project_name: "Project 5",
    client_name: "Customer E",
    alamat_sampling: "Location 5",
    contact_person: "Contact Person 5",
    valuasi_proyek: 30000,
    created_at: "2023-10-14",
  },
  {
    _id: "6",
    no_penawaran: "PNW6",
    project_name: "Project 6",
    client_name: "Customer F",
    alamat_sampling: "Location 6",
    contact_person: "Contact Person 6",
    valuasi_proyek: 35000,
    created_at: "2023-10-14",
  },
  {
    _id: "7",
    no_penawaran: "PNW7",
    project_name: "Project 7",
    client_name: "Customer G",
    alamat_sampling: "Location 7",
    contact_person: "Contact Person 7",
    valuasi_proyek: 40000,
    created_at: "2023-10-14",
  },
  {
    _id: "8",
    no_penawaran: "PNW8",
    project_name: "Project 8",
    client_name: "Customer H",
    alamat_sampling: "Location 8",
    contact_person: "Contact Person 8",
    valuasi_proyek: 45000,
    created_at: "2023-10-14",
  },
  {
    _id: "9",
    no_penawaran: "PNW9",
    project_name: "Project 9",
    client_name: "Customer I",
    alamat_sampling: "Location 9",
    contact_person: "Contact Person 9",
    valuasi_proyek: 50000,
    created_at: "2023-10-14",
  },
  {
    _id: "10",
    no_penawaran: "PNW10",
    project_name: "Project 10",
    client_name: "Customer J",
    alamat_sampling: "Location 10",
    contact_person: "Contact Person 10",
    valuasi_proyek: 55000,
    created_at: "2023-10-14",
  },
  {
    _id: "11",
    no_penawaran: "PNW11",
    project_name: "Project 11",
    client_name: "Customer K",
    alamat_sampling: "Location 11",
    contact_person: "Contact Person 11",
    valuasi_proyek: 60000,
    created_at: "2023-10-14",
  },
  {
    _id: "12",
    no_penawaran: "PNW12",
    project_name: "Project 12",
    client_name: "Customer L",
    alamat_sampling: "Location 12",
    contact_person: "Contact Person 12",
    valuasi_proyek: 65000,
    created_at: "2023-10-14",
  },
  {
    _id: "13",
    no_penawaran: "PNW13",
    project_name: "Project 13",
    client_name: "Customer M",
    alamat_sampling: "Location 13",
    contact_person: "Contact Person 13",
    valuasi_proyek: 70000,
    created_at: "2024-10-14",
  },
  {
    _id: "14",
    no_penawaran: "PNW14",
    project_name: "Project 14",
    client_name: "Customer N",
    alamat_sampling: "Location 14",
    contact_person: "Contact Person 14",
    valuasi_proyek: 75000,
    created_at: "2023-10-14",
  },
  {
    _id: "15",
    no_penawaran: "PNW15",
    project_name: "Project 15",
    client_name: "Customer O",
    alamat_sampling: "Location 15",
    contact_person: "Contact Person 15",
    valuasi_proyek: 80000,
    created_at: "2023-10-14",
  },
];
