import Bottombar from "@/components/Bottombar";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import getSessionServer from "@/lib/actions/getSessionServer";
import {
  getProjectByDivision,
  getProjectsByAcc,
} from "@/lib/actions/sampling.actions";
import { Project } from "@/lib/models/project.model";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lab Karsa Buana",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSessionServer();

  const user = session?.user || "";
  const role = user ? user?.role.toUpperCase() : "";

  let res = null;
  let data: Project[] = [];

  return (
    <>
      <main className="flex flex-row ">
        <Sidebar />
        <section className="flex flex-col sm:min-h-screen items-center flex-1 pt-2 px-6 pb-10 max-lg:pb-32 sm:px-10 bg-[#F8F8F8] overflow-auto">
          <div className="w-full ">
            <Topbar
              projects={data ? data : []}
              data={session ? session : null}
            />
            {children}
          </div>
        </section>
      </main>

      <Bottombar />
    </>
  );
}
