import Bottombar from "@/components/Bottombar";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import getSessionServer from "@/lib/actions/getSessionServer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lab Karsa Buana",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getSessionServer();

  if (data) console.log(data.user);

  return (
    <>
      <main className="flex flex-row ">
        <Sidebar />
        <section className="flex flex-col sm:min-h-screen items-center flex-1 pt-2 px-6 pb-10 max-lg:pb-32 sm:px-10 bg-[#F8F8F8] overflow-auto">
          <div className="w-full ">
            <Topbar data={data ? data : null} />
            {children}
          </div>
        </section>
      </main>

      <Bottombar />
    </>
  );
}
